blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60 * 15)(PostListView.as_view()), name='list_post'),
    path('post/<int:pk>/detail/', PostDetailView.as_view(), name='detail_post'),
    path('post/create/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from mailer.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mailer/', include('mailer.urls', namespace='mailer')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', cache_page(60 * 15)(HomePageView.as_view()), name='home'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое статьи')
    image = models.ImageField(upload_to='blog_images/', verbose_name='Изображение', null=True, blank=True)
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    published_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/forms.py
from blog.models import Post
from mailer.forms import StyleFormMixin
from django import forms


class PostForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.forms import PostForm
from blog.models import Post

from django.urls import reverse_lazy


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'posts'


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:list_post')


class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:list_post')


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'mailer/client_confirm_delete.html'
    success_url = reverse_lazy('blog:list_post')

blog/templates/post_confirm_delete.html
{% extends 'mailer/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост "{{ object.pk }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list_post' %}" class="btn btn-warning">Отмена</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/post_detail.html
{% extends 'mailer/base.html' %}

{% load my_tags %}
{% block content%}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.title|title}}<p>
                          {{object.published_date}}<p>
                        Просмотры {{object.views_count}}</p></h4>

                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.content }}</h1>

                    <ul class="list-unstyled mt-3 mb-4 text-start m-3" style="padding-left: 10px; text-align: left">
                       {% if post.image %}
                         <img class="card-img-top"
                              src="{{ blog.image|mymedia }}"
                              alt="Card image cap"
                         style="max-width: 30%; height: auto;">
                        {% endif %}
                        <div class="card-body">

                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/post_form.html
{% extends "mailer/base.html" %}

{% block content %}
<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
         <h3 class="card-title">

           {% if form.instance.id %}
             Редактирование поста
          {% else %}
            Добавление нового поста
          {% endif %}
            </h3>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
              {% if object %}
                Сохранить
              {% else %}
                Создать
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/post_list.html
{% extends "mailer/base.html" %}

{% block title %}
    Список постов
{% endblock %}

{% block text %}
    Ниже представлен список наших замечательных постов.
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Посты:</h2>
                 <a href="{% url 'blog:create_post' %}" class="btn btn-outline-primary">Создать новый пост</a>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Заголовок поста</th>
                            <th>Содержимое поста</th>
                          <th>Количество просмотров</th>
                          <th>Дата публикации поста</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td>{{ post.title }}</td>
                                <td>{{ post.content }}</td>
                              <td>{{ post.views_count }}</td>
                              <td>{{ post.published_date }}</td>
                                <td>
                                     <a href="{% url 'blog:detail_post' post.pk %}" type="button" class="btn btn-primary">View</a>
                                     <a href="{% url 'blog:update_post' post.pk %}" type="button" class="btn btn-primary">Update</a>
                                 <a href="{% url 'blog:delete_post' post.pk %}" type="button" class="btn btn-danger">Delete</a>
                            </tr>


                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">На данный момент нет постов.</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
                  <div class="btn-group">



                        </div>
            </div>
        </div>
    </div>
{% endblock %}