blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60 * 15)(PostListView.as_view()), name='list_post'),
    path('post/<int:pk>/detail/', PostDetailView.as_view(), name='detail_post'),
    path('post/create/', PostCreateView.as_view(), name='create_post'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='update_post'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from mailer.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mailer/', include('mailer.urls', namespace='mailer')),
    path('user/', include('user.urls', namespace='user')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', cache_page(60 * 15)(HomePageView.as_view()), name='home'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from user.apps import UserConfig
from user.views import RegisterView, UserUpdateView, generate_new_password

app_name = UserConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),


]

user/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class CustomUserManager(BaseUserManager):
    """
    Custom manager for User.
    """
    def create_superuser(self, email, password=None, **extra_fields):
        """
        Create and return a superuser with the given email and password.
        """
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    groups = models.ManyToManyField('auth.Group', blank=True, related_name='custom_user_set')
    user_permissions = models.ManyToManyField('auth.Permission', blank=True, related_name='custom_user_set')

    objects = CustomUserManager()  # Используйте ваш собственный менеджер

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from mailer.forms import StyleFormMixin
from user.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

user/views.py
import random

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from user.forms import UserRegisterForm, UserForm
from user.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Поздравляем, до окончания регистрации осталось совсем чуть-чуть',
            message='Для завершения регистрации перейдите по ссылке http://127.0.0.1:8000/',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('mailer:index')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('mailer:index'))

user/templates/login.html
{% extends 'mailer/base.html' %}

{% block content %}
            <div class="row justify-content-center">

<form method="post" class="row" enctype="multipart/form-data">
  <div class="col-12">
      <div class="col-3"></div>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
            Вход
        </h3>
      </div>
      <div class="card-body">

          {% csrf_token %}
          {{ form.as_p }}


          <button type="submit" class=" btn btn-success">Войти</button>

      </div>
      <div class="card-footer"></div>
    </div>
  </div>
</form>
                            </div>

{% endblock %}

user/templates/register.html
{% extends 'mailer/base.html' %}

{% block content %}
            <div class="row justify-content-center">

<form method="post" class="row" enctype="multipart/form-data">
  <div class="col-12">
      <div class="col-3"></div>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
            Регистрация
        </h3>
      </div>
      <div class="card-body">

          {% csrf_token %}
          {{ form.as_p }}


          <button type="submit" class=" btn btn-success">Регистрация</button>

      </div>
      <div class="card-footer"></div>
    </div>
  </div>
</form>
                            </div>

{% endblock %}

user/templates/user_form.html
{% extends 'mailer/base.html' %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class=" btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'user:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>

        </div>
    </div>
</div>
{% endblock %}